### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by pickaxe828** [fkohlgrueber/viu#1]
`pip install viu` works on windows,
but:
```shell
> viu
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\viu.exe\__main__.py", line 4, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\viu\viu.py", line 8, in <module>
    import tty
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
```

**Comment by fkohlgrueber** [comment]
This project uses `termios`, which is only available on Unix. If you want to use it on Windows, you can use the Windows Subsystem for Linux (WSL).
